Fix the problem caused by commit. see description
Fix the problem caused by this commit : https://github.com/Significant-Gravitas/Auto-GPT/commit/680c7b5aaaa9bc088e7f16451227daac8122e4d4

This previous commit breaks Auto GPT on Linux Debian with Pythin 3.11. 

Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "/usr/share/Auto-GPT/autogpt/main.py", line 5, in
autogpt.cli.main()
File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/click/core.py", line 1635, in invoke
rv = super().invoke(ctx)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/Auto-GPT/autogpt/cli.py", line 87, in main
from autogpt.agent.agent import Agent
File "/usr/share/Auto-GPT/autogpt/agent/init.py", line 1, in
from autogpt.agent.agent import Agent
File "/usr/share/Auto-GPT/autogpt/agent/agent.py", line 3, in
from autogpt.app import execute_command, get_command
File "/usr/share/Auto-GPT/autogpt/app.py", line 7, in
from autogpt.commands.web_requests import scrape_links, scrape_text
File "/usr/share/Auto-GPT/autogpt/commands/web_requests.py", line 16, in
memory = get_memory(CFG)
^^^^^^^^^^^^^^^
File "/usr/share/Auto-GPT/autogpt/memory/init.py", line 81, in get_memory
memory = LocalCache(cfg)
^^^^^^^^^^^^^^^
File "/usr/share/Auto-GPT/autogpt/config/singleton.py", line 15, in call
cls._instances[cls] = super(Singleton, cls).call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/Auto-GPT/autogpt/memory/local.py", line 41, in init
workspace_path = Path(cfg.workspace_path)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/pathlib.py", line 872, in new
self = cls._from_parts(args)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/pathlib.py", line 510, in _from_parts
drv, root, parts = self._parse_args(args)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/pathlib.py", line 494, in _parse_args
a = os.fspath(a)
^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType