Fix docker compose example volumes
1. The `auto_gpt_workspace` is created in the docker container inside `/app/autogpt/auto_gpt_workspace` and not `/app/auto_gpt_workspace`, so it was not being correctly synced from host to container.

2. Docker compose does not allow single file volumes, uncommenting the lines removed in this PR would cause a directory to be created and the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 90, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 135, in run_auto_gpt
    ai_config = construct_main_ai_config()
  File "/app/autogpt/prompts/prompt.py", line 88, in construct_main_ai_config
    config = AIConfig.load(CFG.ai_settings_file)
  File "/app/autogpt/config/ai_config.py", line 75, in load
    with open(config_file, encoding="utf-8") as file:
IsADirectoryError: [Errno 21] Is a directory: 'ai_settings.yaml'
```